controllers:
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 100
    robot_state_controller:
      type: robot_state_controller/RobotStateController
      publish_rate: 100

    gimbal_calibration_controller:
      type: rm_calibration_controllers/MechanicalCalibrationController
      actuator: [ pitch_joint_motor ]
      velocity:
        joint: pitch_joint
        search_velocity: 6.28
        vel_threshold: 1e-2
        pid: { p: 0.3, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }
    trigger_calibration_controller:
      type: rm_calibration_controllers/MechanicalCalibrationController
      actuator: [ trigger_joint_motor ]
      velocity:
        joint: trigger_joint
        search_velocity: 3.1415
        vel_threshold: 0.2
        pid: { p: 0.3, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }
    barrel_calibration_controller:
      type: rm_calibration_controllers/MechanicalCalibrationController
      actuator: [ barrel_joint_motor ]
      velocity:
        joint: barrel_joint
        search_velocity: -6.28
        vel_threshold: 0.001
        pid: { p: 3.0, i: 15.0, d: 0.0, i_clamp_max: 0.2, i_clamp_min: -0.2, antiwindup: true }

    chassis_controller:
      type: rm_chassis_controllers/OmniController
      # ChassisBase
      publish_rate: 100
      enable_odom_tf: true
      publish_odom_tf: false
      power:
        effort_coeff: 2.35
        vel_coeff: 0.00875
        power_offset: -9.8
      twist_angular: 0.5233
      timeout: 0.1
      max_odom_vel: 10.0
      pid_follow: { p: 10, i: 0, d: 0.02, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
      twist_covariance_diagonal: [ 0.001, 0.001, 0.001, 0.001, 0.001, 0.001 ]


      # OmniController
      wheels:
        left_front:
          pose: [ 0.1895, 0.10, 0. ]
          roller_angle: -0.785
          joint: left_front_wheel_joint
          <<: &wheel_setting
            radius: 0.07625
            pid: { p: 0.3, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
        right_front:
          pose: [ 0.1895, -0.10, 0. ]
          roller_angle: 0.785
          joint: right_front_wheel_joint
          <<: *wheel_setting
        left_back:
          pose: [ -0.1895, 0.10, 0. ]
          roller_angle: 0.785
          joint: left_back_wheel_joint
          <<: *wheel_setting
        right_back:
          pose: [ -0.1895, -0.10, 0. ]
          roller_angle: -0.785
          joint: right_back_wheel_joint
          <<: *wheel_setting

    orientation_controller:
      type: rm_orientation_controller/Controller
      publish_rate: 100
      name: "gimbal_imu"
      frame_source: "odom"
      frame_target: "base_link"

    gimbal_controller:
      type: rm_gimbal_controllers/Controller
      yaw:
        joint: "yaw_joint"
        pid: { p: 20, i: 34.85, d: 0.82, i_clamp_max: 0.3, i_clamp_min: -0.3, antiwindup: true, publish_state: true }
        k_chassis_vel: 0.045
      pitch:
        joint: "pitch_joint"
        pid: { p: 22.0, i: 80, d: 0.75, i_clamp_max: 0.6, i_clamp_min: -0.6, antiwindup: true, publish_state: true }
      chassis_vel:
        num_data: 100
        debug: true
      imu_name: "gimbal_imu"
      feedforward:
        gravity: 0.0
        enable_gravity_compensation: false
        mass_origin: [ 0.0, 0.0, 0.0 ]
      bullet_solver:
        resistance_coff_qd_10: 0.0
        resistance_coff_qd_15: 0.0
        resistance_coff_qd_16: 0.0
        resistance_coff_qd_18: 0.0
        resistance_coff_qd_30: 0.0
        g: 9.81
        delay: 0.03
        dt: 0.001
        timeout: 0.001
        publish_rate: 50
        max_track_target_vel: 5.0

    shooter_controller:
      type: rm_shooter_controllers/Controller
      publish_rate: 50
      friction_left:
        joint: "left_friction_wheel_joint"
        pid: { p: 0.0007, i: 0.005, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: true }
      friction_right:
        joint: "right_friction_wheel_joint"
        pid: { p: 0.0007, i: 0.005, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: true }
      trigger:
        joint: "trigger_joint"
        pid: { p: 50.0, i: 0.0, d: 1.3, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true, publish_state: true }
      push_per_rotation: 9
      push_qd_threshold: 0.90
      block_effort: 2.2
      block_speed: 0.1
      block_duration: 0.05
      block_overtime: 0.5
      anti_block_angle: 0.46
      anti_block_threshold: 0.1
      forward_push_threshold: 0.28
      exit_push_threshold: 0.3
      extra_wheel_speed: 733.0

gimbal_calibration:
  - start_controllers:
      - controllers/gimbal_calibration_controller
    stop_controllers:
      - controllers/gimbal_controller
    services_name:
      - /controllers/gimbal_calibration_controller/is_calibrated
shooter_calibration:
  - start_controllers:
      - controllers/trigger_calibration_controller
    stop_controllers:
      - controllers/shooter_controller
    services_name:
      - /controllers/trigger_calibration_controller/is_calibrated

controllers_list:
  state_controllers:
    - controllers/joint_state_controller
    - controllers/robot_state_controller
  main_controllers:
    - controllers/chassis_controller
    - controllers/gimbal_controller
    - controllers/shooter_controller
    - controllers/orientation_controller
  calibration_controllers:
    - controllers/trigger_calibration_controller
    - controllers/gimbal_calibration_controller

robot_decision:
  gimbal:
    topic: "/controllers/gimbal_controller/command"
    max_yaw_vel: 3.0
    max_pitch_vel: 1.3
    track_timeout: 0.5
    target_cost_function:
      k_pos: 1.0
      k_vel: 1.0
      k_hp: 1.0
      k_freq: 1.0
      timeout: 0.05
  chassis:
    topic: "/cmd_chassis"
    accel_x:
      - [ 50.0,99.0 ]
    accel_y:
      - [ 50.0,99.0 ]
    accel_z:
      - [ 50.0,99.0 ]
    safety_power: 150
    capacitor_threshold: 0.1
    charge_power: 20
    extra_power: 30
    burst_power: 240
    buffer_threshold: 10
    power_gain: 0.85
  vel2d:
    topic: "/cmd_vel"
    power_limit_topic: "/cmd_chassis"
    max_linear_x:
      - [ 150.0,3.14 ]
    max_linear_y:
      - [ 150.0,3.14 ]
    max_angular_z:
      - [ 150.0,6.7 ]
    gyro_move_reduction: 0.3
    gyro_rotate_reduction: 0.7
  shooter:
    topic: "/controllers/shooter_controller/command"
    gimbal_error_tolerance: 0.15
    target_acceleration_tolerance: 99.0
    accleration_moving_average_num: 10
    speed_10m_per_speed: 10.0
    speed_15m_per_speed: 13.5
    speed_16m_per_speed: 16.0
    speed_18m_per_speed: 15.72
    speed_30m_per_speed: 24.2
    heat_limit:
      low_shoot_frequency: 20
      high_shoot_frequency: 20
      burst_shoot_frequency: 20
      safe_shoot_frequency: 2
      heat_coeff: 12.0
      minimal_shoot_frequency: 1
      type: "ID1_17MM"
  barrel:
    topic: "/controllers/barrel_controller/command"
    joint: "barrel_joint"
    id1_point: 0.45
    id2_point: 1.62
    is_double_barrel: false
    check_switch_threshold: 0.02
    check_launch_threshold: 0.02
    frequency_threshold: 17.0
    ready_duration: 0.5
    switching_duration: 0.5
  patrol:
    goal_list: [
        #  x,y,yaw
        [ 1.03, -1.56, 1.57 ],
        [ 2.14, -0.41, 1.57 ],
        [ 0.0, 0.0, 1.57 ]
    ]
    search_radius: 0.75
    search_list: [
        [0, 1],
        [0, -1],
        [1, 0],
        [-1, 0],
        [1.412, 1.412],
        [1.412, -1.412],
        [-1.412, 1.412],
        [-1.412, -1.412],
    ]